language: python

python:
    - 3.6

virtualenv:
    system_site_packages: true

compiler:
    - g++

before_install:
    #- "sudo apt-get -qq update"
    # Non-pip dependency
    #- "sudo apt-get install -y libffi-dev libssl-dev python-dev"
    #- "pip install --user pyOpenSSL ndg-httpsclient pyasn1"
    #- "pip install --user urllib3[secure] --upgrade"
    #- "pip install --user requests[security] --upgrade"
    # GalSim dependencies
    #- "sudo apt-get install -y libfftw3-dev libav-tools libeigen3-dev cmake"
    #- "pip install --user pybind11"
    # Install GalSim
    #- "pip install --user galsim"
   
cache:
    ccache: true
    pip: true

install:
    # Install SLRealizer dependencies
    - "pip install -e ."

script:
    - "python setup.py test"

after_success:
    - codecov